### ISSUE TITLE
Detect broken links in properties (previously known as frontmatter or YAML)

### ISSUE THREAD

**Issue by claremacrae** [ipshing/obsidian-broken-links#5]
Obsidian has introduced a [Properties](https://help.obsidian.md/Editing+and+formatting/Properties) UI that makes it easy to add links in the frontmatter/yaml.

It would be really helpful if this plugin could detect any broken links in frontmatter.

### Test case

I am not sure if the following is a complete list of examples for testing, but it is the range of links I'm aware of in properties so far....

1. Create a file called `Demo.md`
2. Paste in this content:

```test
---
broken link to file: "[[I Do not exist - single link]]"
broken link to heading: "[[Demo#No such heading]]"
list of broken links:
  - "[[I Do not exist - in list]]"
  - "[[Demo#No such heading linked from list]]"
---

# Demo
```

**Expected results:**

4 broken links shown

**Actual results:**

No broken links shown.

**Comment by claremacrae** [comment]
One hard part of this is how to navigate to the problem line. I'm not sure if that is possible. 

It would likely be good enough to just open the problem file, and let the user navigate to the problem entry - via one of:

- the "File properties" in the side bar
- or the "Live Preview" properties at the top of the file

**Comment by ipshing** [comment]
This is live in version [1.2.0](https://github.com/ipshing/obsidian-broken-links/releases/tag/1.2.0). At this time, there doesn't appear to be an efficient way to highlight the link because Obsidian doesn't track the line/col of links in frontmatter (that I can find). It will, however, open the file and, if in editor mode, scroll to the top of the document.
